### ISSUE TITLE
3 features

### ISSUE THREAD

**Issue by MatthewBregg** [JohnReedLOL/Nineteen_Characters#108]
When attacking a monster with a ranged attack, it currently magically does an invisible range attack in response. A monster should either chase after you, or show that it did a range attack also.
Also, tile damange from attacks and effects should dissapate after a few turns...
Lastly, calling observe on a tile with a monster doesn't mention the monster...

**Comment by JohnReedLOL** [comment]
1. Modify the behavior of Monster.recieveAttack so that instead of directly damaging anyone who attacks you, it does something else (if the entity who attacked you is facing up, call getMapRelation.sendAttackInDirection( DOWN )

^ just an example ^… you can make it do anything as long as it makes sense and works correctly. 

Anyway, the point of the onTurn function was so that every entity/avatar/item has the ability to do something each turn. You could make an onTurn function in Entity, Override it in Avatar, and make the Override heal 1 health. I can take care of calling on turn for every entity whenever the map receives a command. 

| Squashed these three comments together - Matt

**Comment by JohnReedLOL** [comment]
^ just an example ^… you can make it do anything as long as it makes sense and works correctly.

**Comment by JohnReedLOL** [comment]
Anyway, the point of the onTurn function was so that every entity/avatar/item has the ability to do something each turn. You could make an onTurn function in Entity, Override it in Avatar, and make the Override heal 1 health. I can take care of calling on turn for every entity whenever the map receives a command.

**Comment by MatthewBregg** [comment]
Ok, thanks, I'll look into that later, need to rest atm. 
Probably work on those 3 features tommorow. 

I was planning on making monster attempt to move towards the player, but then it'd be awkward as it'd take a step forward and stop. Could make on turn continue moving in the direction of attack for certain amount of time...... Alternatively, just give the monster a visible ranged attack. 

Also, I meant have the tiles rever to former decal, rather than healing. 

I'll have to see how area of effect decorators work, but I'll probably add a setDecalForXTurns method, that when the mapvisits eachs maptile, each maptile decrements it. 

Observe is more complex, I'd have to look at it more to even know where to start.

**Comment by JohnReedLOL** [comment]
Wait. We need to talk about all the queues and the infinite loop problem and stuff. Right now, the online version works in the dungeon, but my screen won't refresh if someone else sends commands to my map. I have to press a key for the screen to refresh. I can either make it so that when one person moves, everybody IO_Bundles sent to them (not a good idea) or I can ask the Controller to ask for a new IO_Bundle every 500 milliseconds if no key command interrupt was received. I think the second would be better. I also added a lot of print statements to master to make it easier to find out what is causing the bug. But I think the whole queue thing is a bad idea and that you don't actually need to store key commands at all - just run the first command that you receive and if the user is too quick and overwhelmed the controller with too many commands just ignore those.

**Comment by MatthewBregg** [comment]
Don't just close this bug report, it's still valid, we can talk about this, but else where. Can you reopen this?

**Comment by MatthewBregg** [comment]
As for the above, yeah, that could be set simply by reducing the sleep.  
I think the queues are a better solution than not having the queues, and it's literally more or less the solution from the book. 
Dropping commands should be a last resort.

**Comment by MatthewBregg** [comment]
The only remaining feature that is needed is monsters reponsding properly to ranged attacks.

**Comment by MatthewBregg** [comment]
Done
